### ISSUE TITLE
Cannot add magnet links

### ISSUE THREAD

**Issue by rsgranne** [bittorrent/btc#2]
It appears that magnet links do not work, as I get the following error:

~~~~~
$ btc add magnet:?xt=urn:btih:91ea15451a642d7ff25485e0441ae869b86b4467&dn=ubuntu-12.04.2-desktop-i386.iso&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80&tr=udp%3A%2F%2Ftracker.publicbt.com%3A80&tr=udp%3A%2F%2Ftracker.istole.it%3A6969&tr=udp%3A%2F%2Ftracker.ccc.de%3A80&tr=udp%3A%2F%2Fopen.demonii.com%3A1337
[1] 30326
[2] 30327
[3] 30328
[4] 30329
[5] 30330
[6] 30331
[2]   Done                    dn=ubuntu-12.04.2-desktop-i386.iso
[3]   Done                    tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80
[4]   Done                    tr=udp%3A%2F%2Ftracker.publicbt.com%3A80
[5]-  Done                    tr=udp%3A%2F%2Ftracker.istole.it%3A6969

scott@box:~/Desktop$ Traceback (most recent call last):
  File "/usr/local/bin/btc", line 8, in <module>
    load_entry_point('btc==0.1', 'console_scripts', 'btc')()
  File "/Library/Python/2.7/site-packages/btc/btc.py", line 169, in main
    module.main()
  File "/Library/Python/2.7/site-packages/btc/btc_add.py", line 27, in main
    torrent = utils.get(args.value, utf8=False)
  File "/Library/Python/2.7/site-packages/btc/utils.py", line 109, in get
    response, content = make_request(h, host + selector, headers=headers)
  File "/Library/Python/2.7/site-packages/btc/utils.py", line 67, in make_request
    return http.request(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/httplib2/__init__.py", line 1454, in request
    proxy_info=proxy_info)
  File "/Library/Python/2.7/site-packages/httplib2/__init__.py", line 860, in __init__
    httplib.HTTPConnection.__init__(self, host, port, strict)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 693, in __init__
    self._set_hostport(host, port)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 718, in _set_hostport
    raise InvalidURL("nonnumeric port: '%s'" % host[i+1:])
httplib.InvalidURL: nonnumeric port: ''

[1]-  Exit 1                  btc add magnet:?xt=urn:btih:91ea15451a642d7ff25485e0441ae869b86b4467
[6]+  Done                    tr=udp%3A%2F%2Ftracker.ccc.de%3A80
~~~~~~

**Comment by jpcottin** [comment]
merge to master
